import "./globals.css";
import { Poppins } from "next/font/google";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import { twJoin } from "tailwind-merge";

const font = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={twJoin(font.className, "h-screen")}>
        <Theme className="h-full w-full">
          {children}
        </Theme>
      </body>
    </html>
  );
}
